### ISSUE TITLE
Error: Failed to optimize the project: 'ShellCommand' object has no attribute '_program'

### ISSUE THREAD

**Issue by parthivgls** [duaraghav8/dockershrink#1]
It looks like the issue occurs when I try to shrink a Docker file, which has nothing to do with npm.

I tried to shrink this. 

https://gitlab.com/flectra-hq/docker/-/blob/master/3.0/Dockerfile?ref_type=heads

**Comment by Avijit-ap** [comment]
Yes, as per the docs it only helpful for nodejs projects 
![image](https://github.com/user-attachments/assets/76a7c219-d18a-4908-95ef-3aba95096aad)

**Comment by SamJUK** [comment]
+1 having the same issue with the distributed version (pipx). The following patch resolves it, although is likely the wrong solution.

```patch
diff --git a/dockershrink/dockerfile/shell_command.py b/dockershrink/dockerfile/shell_command.py
index c8c7f55..4e48d54 100644
--- a/dockershrink/dockerfile/shell_command.py
+++ b/dockershrink/dockerfile/shell_command.py
@@ -124,6 +124,7 @@ class ShellCommand:
         self._index = index
         self._command = cmd
         self._command_form = cmd_form
+        self._program = ''

         self._parse_command()


```
