### ISSUE TITLE
Verbose Output

### ISSUE THREAD

**Issue by SamJUK** [duaraghav8/dockershrink#2]
Currently if the program fails with an exception, we get a generalised error message which seems to provide too little information for useful error reporting.  E.G `Error: Failed to optimize the project: 'NoneType' object has no attribute 'parent_stage'`.

Having a verbose mode (`-v | --verbose`), that prints out a traceback for the exception would be helpful for error reporting.

**Comment by avijit-shihaan** [comment]
> Currently if the program fails with an exception, we get a generalised error message which seems to provide too little information for useful error reporting. E.G `Error: Failed to optimize the project: 'NoneType' object has no attribute 'parent_stage'`.
> 
> Having a verbose mode (`-v | --verbose`), that prints out a traceback for the exception would be helpful for error reporting.

Can you please guide how to reproduce the issue?

**Comment by duaraghav8** [comment]
Agreed on the verbose mode, will add it.
Also, can you share your dockerfile (or how I can reproduce this, as avijit pointed out)?

**Comment by SamJUK** [comment]
The error is actually the same I reported separately within #3, and the same example Dockerfile can be used to reproduce the error. 

```Dockerfile
FROM alpine

WORKDIR /application

RUN apk update
RUN apk add rsync git make curl libzip-dev tar openssh patch bash jq

ENTRYPOINT ["/bin/sh"]
```

**Comment by duaraghav8** [comment]
Verbose option is now merged into main (https://github.com/duaraghav8/dockershrink/pull/4), will be out with the next release. Thanks for this suggestion!

I ran it on the code you shared above, will be investigating the issue separately.

```bash
dockershrink optimize --verbose
* Reading Dockerfile
* No .dockerignore file found
* No package.json found in the default paths


Error: Failed to optimize the project: 'NoneType' object has no attribute 'parent_stage'

Traceback (most recent call last):
  File "/Users/raghav/Desktop/code/dockershrink/dockershrink/cli.py", line 167, in optimize_command
    response = project.optimize_docker_image(ai_service)
  File "/Users/raghav/Desktop/code/dockershrink/dockershrink/project/project.py", line 493, in optimize_docker_image
    self._dockerfile_use_depcheck()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/raghav/Desktop/code/dockershrink/dockershrink/project/project.py", line 247, in _dockerfile_use_depcheck
    depcheck_layer: df.RunLayer = self.dockerfile.insert_after_layer(
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        last_copy_layer, "RUN npx depcheck"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/raghav/Desktop/code/dockershrink/dockershrink/dockerfile/dockerfile.py", line 326, in insert_after_layer
    stage = layer.parent_stage()
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parent_stage'
```

**Comment by duaraghav8** [comment]
0.1.4 is now released
